#!/usr/bin/env python3
"""Build the demo workspace the manual screenshots are taken against.

The repositories are synthetic on purpose. Screenshots of real work leak
branch names, colleagues' addresses and directory layouts, and they cannot be
regenerated by anyone else — so every commit, author and path here is
invented, and the whole workspace is rebuilt from scratch on each run.

The states are chosen to make the dashboard's colours mean something: a repo
that is behind, one with uncommitted work, one stopped mid-merge with a
conflict, one clean. A screenshot where everything is green shows none of it.

    python3 docs/gen_demo.py [workspace]     # default: /tmp/gdt-demo
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

# Fixed timestamps so a regenerated workspace produces identical screenshots
# rather than a diff on every date in every image.
BASE_TS = 1755000000  # 2025-08-12T...

AUTHORS = [
    ("Aya Tanaka", "aya@example.com"),
    ("Ben Ortiz", "ben@example.com"),
    ("Chen Wei", "chen@example.com"),
    ("Dara Osei", "dara@example.com"),
]


def run(cwd: Path, *args: str, ts: int | None = None, check: bool = True) -> str:
    env = dict(os.environ)
    env["GIT_TERMINAL_PROMPT"] = "0"
    if ts is not None:
        stamp = f"{ts} +0900"
        env["GIT_AUTHOR_DATE"] = stamp
        env["GIT_COMMITTER_DATE"] = stamp
    p = subprocess.run(
        ["git", *args], cwd=cwd, env=env, capture_output=True, text=True
    )
    if check and p.returncode != 0:
        raise SystemExit(f"git {' '.join(args)} in {cwd} failed:\n{p.stderr}")
    return p.stdout


def init(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    run(path, "init", "-q", "-b", "main")
    run(path, "config", "user.name", AUTHORS[0][0])
    run(path, "config", "user.email", AUTHORS[0][1])
    run(path, "config", "commit.gpgsign", "false")
    run(path, "config", "core.autocrlf", "false")


def commit(path: Path, files: dict[str, str], message: str, n: int, who: int = 0) -> None:
    for name, body in files.items():
        f = path / name
        f.parent.mkdir(parents=True, exist_ok=True)
        f.write_text(body, encoding="utf-8")
    run(path, "add", "-A")
    name, mail = AUTHORS[who % len(AUTHORS)]
    run(
        path,
        "-c", f"user.name={name}",
        "-c", f"user.email={mail}",
        "commit", "-q", "-m", message,
        ts=BASE_TS + n * 8400,
    )


def publish(path: Path, root: Path) -> Path:
    """Give a repository a local bare origin and push main to it.

    Without a remote, `fetch` in a screenshot only produces "No remote
    configured" — an error where the manual means to show progress.
    """
    bare = root / ".remotes" / f"{path.name}.git"
    bare.parent.mkdir(exist_ok=True)
    run(path, "init", "-q", "--bare", str(bare))
    run(path, "remote", "add", "origin", str(bare))
    run(path, "push", "-q", "-u", "origin", "main")
    return bare


def build(root: Path) -> None:
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)

    # --- api-gateway: clean, tagged, several contributors ------------------
    api = root / "api-gateway"
    init(api)
    commit(api, {"README.md": "# api-gateway\n\nEdge routing and auth.\n"},
           "Initial commit", 1, 0)
    commit(api, {"src/router.go": "package main\n\nfunc route() {}\n"},
           "Add request router", 2, 1)
    commit(api, {"src/auth.go": "package main\n\nfunc verify() bool {\n\treturn true\n}\n"},
           "Verify bearer tokens on every route", 3, 2)
    run(api, "tag", "-a", "v1.2.0", "-m", "Rate limiting and token verification")
    commit(api, {"src/limit.go": "package main\n\nconst burst = 40\n"},
           "Add rate limiting middleware", 4, 1)
    # A change with several hunks across a real-looking file, so the diff
    # pane in the manual shows syntax colour and hunk navigation rather than
    # a single edited line.
    before = """package main

import "time"

type Limiter struct {
	burst  int
	window time.Duration
}

func NewLimiter() *Limiter {
	return &Limiter{burst: 40, window: time.Second}
}

func (l *Limiter) Allow(key string) bool {
	if key == "" {
		return false
	}
	return true
}
"""
    after = """package main

import (
	"sync"
	"time"
)

type Limiter struct {
	mu     sync.Mutex
	burst  int
	window time.Duration
	seen   map[string]int
}

func NewLimiter() *Limiter {
	return &Limiter{burst: 60, window: time.Second, seen: map[string]int{}}
}

func (l *Limiter) Allow(key string) bool {
	if key == "" {
		return false
	}
	l.mu.Lock()
	defer l.mu.Unlock()
	l.seen[key]++
	return l.seen[key] <= l.burst
}
"""
    commit(api, {"src/limit.go": before}, "Extract the limiter into a type", 5, 3)
    commit(api, {"src/limit.go": after},
           "Track per-key usage and raise the burst to 60", 6, 1)
    run(api, "tag", "-a", "v1.3.0", "-m", "Higher burst allowance")
    publish(api, root)

    # --- billing-service: uncommitted work, a stash, a topic branch --------
    billing = root / "billing-service"
    init(billing)
    commit(billing, {"README.md": "# billing-service\n\nInvoicing and tax.\n"},
           "Initial commit", 1, 0)
    commit(billing, {"invoice.py": "def total(lines):\n    return sum(lines)\n"},
           "Extract invoice total calculation", 2, 2)
    commit(billing, {"tax.py": "def apply(amount, rate):\n    return amount * rate\n"},
           "Apply tax at the line level", 3, 0)
    run(billing, "checkout", "-q", "-b", "feature/refunds")
    commit(billing, {"refund.py": "def partial(amount, ratio):\n    return amount * ratio\n"},
           "Sketch partial refunds", 4, 2)
    run(billing, "checkout", "-q", "main")
    # Something stashed, and something still uncommitted.
    (billing / "tax.py").write_text("def apply(amount, rate):\n    return round(amount * rate, 2)\n", encoding="utf-8")
    # Stamp the stash too: `git log --all` sees refs/stash, so an unstamped
    # one would date the repository "today" and make every regenerated
    # screenshot differ from the last.
    run(billing, "stash", "push", "-q", "-m", "half-up rounding experiment",
        ts=BASE_TS + 4 * 8400)
    (billing / "invoice.py").write_text(
        "def total(lines):\n    return sum(line.amount for line in lines)\n", encoding="utf-8")
    (billing / "notes.md").write_text("Rounding rules to confirm with finance.\n", encoding="utf-8")
    publish(billing, root)

    # --- infra-terraform: behind its upstream ------------------------------
    infra = root / "infra-terraform"
    init(infra)
    commit(infra, {"README.md": "# infra-terraform\n\nCluster and network.\n"},
           "Initial commit", 1, 3)
    commit(infra, {"eks.tf": 'variable "node_version" {\n  default = "1.28"\n}\n'},
           "Pin the EKS node group version", 2, 3)
    bare = root / ".remotes" / "infra-terraform.git"
    bare.parent.mkdir(exist_ok=True)
    run(infra, "init", "-q", "--bare", str(bare))
    run(infra, "remote", "add", "origin", str(bare))
    run(infra, "push", "-q", "-u", "origin", "main")
    # Two commits land on the remote that this checkout has not pulled.
    commit(infra, {"eks.tf": 'variable "node_version" {\n  default = "1.29"\n}\n'},
           "Bump the EKS node group to 1.29", 3, 3)
    commit(infra, {"vpc.tf": 'variable "cidr" {\n  default = "10.4.0.0/16"\n}\n'},
           "Widen the VPC CIDR", 4, 1)
    run(infra, "push", "-q", "origin", "main")
    run(infra, "reset", "-q", "--hard", "HEAD~2")

    # --- web-frontend: stopped mid-merge, with a conflict ------------------
    web = root / "web-frontend"
    init(web)
    commit(web, {"README.md": "# web-frontend\n\nCheckout and cart.\n"},
           "Initial commit", 1, 0)
    commit(web, {"checkout.ts": "export const timeout = 30_000;\n"},
           "Add a checkout timeout", 2, 2)
    run(web, "checkout", "-q", "-b", "hotfix/timeout")
    commit(web, {"checkout.ts": "export const timeout = 60_000;\n"},
           "Raise the checkout timeout to 60s", 3, 1)
    run(web, "checkout", "-q", "main")
    commit(web, {"checkout.ts": "export const timeout = 45_000;\n"},
           "Raise the checkout timeout to 45s", 4, 0)
    # Leaves MERGE_HEAD and a conflicted file behind, which is the state the
    # dashboard's ⚠MERGE badge and conflict count exist to surface.
    run(web, "merge", "hotfix/timeout", check=False)
    run(web, "checkout", "-q", "-b", "feature/cart", "hotfix/timeout", check=False)
    run(web, "checkout", "-q", "main", check=False)
    publish(web, root)

    # --- design-system: a second worktree ----------------------------------
    design = root / "design-system"
    init(design)
    commit(design, {"README.md": "# design-system\n\nTokens and components.\n"},
           "Initial commit", 1, 3)
    commit(design, {"tokens.json": '{\n  "radius": 8\n}\n'},
           "Publish the first token set", 2, 3)
    run(design, "branch", "release/2.0")
    run(design, "worktree", "add", "-q", str(root / "design-system-2.0"), "release/2.0")
    publish(design, root)

    print(f"demo workspace: {root}")
    for p in sorted(root.iterdir()):
        if p.is_dir() and not p.name.startswith("."):
            print(f"  {p.name}")


if __name__ == "__main__":
    build(Path(sys.argv[1] if len(sys.argv) > 1 else "/tmp/gdt-demo"))
