"""Task-oriented bilingual content consumed by gen_manual.py."""


def sections(t):
    return [
        ("versions", t("Release or development version?", "リリース版と開発版"), [
            ("p", t(
                'This manual describes v0.5.0. The installer downloads the latest published release. First-run guidance, Home freshness context, the O tool menu, W workspace, untracked-file diffs and cancellable discovery are included in v0.4.0. v0.5.0 adds title-bar mouse navigation and selection in Settings, Repository Finder, Global Members and Commit Search. See the <a href="https://github.com/orapli/git-dashboard-tui/blob/main/CHANGELOG.md">changelog</a>. For older releases, read the README at the corresponding tag. Development main may contain later unreleased changes: a command-line surface (<code>PATH</code> and <code>--json</code>), commit-search filters, branch-scoped CI with richer pull-request signals, Home rows that distinguish unknown from fine, contextual help, <kbd>y</kbd> yank and user-defined work-tool commands — plus a large refresh speed-up.',
                'このマニュアルはv0.5.0を説明します。インストーラは最新の公開リリースを取得します。初回ガイド、Homeの取得状態、Oメニュー、W一覧、未追跡ファイルの差分、中止できる走査はv0.4.0に含まれます。v0.5.0ではタイトルバーのマウス移動と、設定・検出・横断メンバー・コミット検索のクリック操作を追加しています。<a href="https://github.com/orapli/git-dashboard-tui/blob/main/CHANGELOG.md">変更履歴</a>を参照してください。過去版は対応タグのREADMEで確認できます。開発用mainにはその後の未リリース変更が含まれる場合があります。コマンドライン（<code>PATH</code> と <code>--json</code>）、コミット検索のフィルタ、ブランチ単位のCIとPR情報の拡充、状態不明と正常を区別するHome行、画面別ヘルプ、<kbd>y</kbd> でのコピー、独自の作業ツールコマンド、そして更新処理の大幅な高速化が該当します。')),
            ("code", t(
                'cargo install --git https://github.com/orapli/git-dashboard-tui --branch main --locked',
                'cargo install --git https://github.com/orapli/git-dashboard-tui --branch main --locked')),
            ("p", t('Building main requires Rust 1.88 or later and a native linker/toolchain. Pre-built release binaries do not require Rust. To pin a release with the installer, use <code>VERSION=v0.5.0 sh</code> in place of <code>sh</code>.',
                    'mainのビルドにはRust 1.88以上とネイティブのリンカ・ビルド環境が必要です。配布バイナリにはRustは不要です。インストーラでバージョンを固定する場合は <code>sh</code> を <code>VERSION=v0.5.0 sh</code> に置き換えます。')),
        ]),
        ("tasks", t("Task walkthroughs", "目的別の操作手順"), [
            ("cols", [
                (t('Start the day', '作業を始める'), t('Home: press <kbd>r</kbd> to reread local data. If you need current remote refs, use <kbd>f</kbd> on one repository or <kbd>F</kbd> for the filtered list. Press <kbd>n</kbd>, select a row and read the attention reason before opening it with <kbd>Enter</kbd>.', 'Homeで <kbd>r</kbd> を押してローカル情報を再読込します。リモート参照の更新が必要なら、1件は <kbd>f</kbd>、絞り込み中の一覧は <kbd>F</kbd>。<kbd>n</kbd> で要対応に絞り、理由を読んで <kbd>Enter</kbd> で詳細を開きます。')),
                (t('Inspect and edit', '差分を確認して編集する'), t('In Status (<kbd>1</kbd>), select a file and press <kbd>Enter</kbd>. In Diff, use <kbd>n</kbd>/<kbd>p</kbd> for hunks and <kbd>b</kbd> for blame. <kbd>O</kbd> opens your tools; configure the editor with <kbd>c</kbd>. After GUI edits, return to Home or Repo and press <kbd>r</kbd>. Returning from a terminal tool refreshes the diff file list and keeps the selected file and scroll position when that file remains.', 'Status（<kbd>1</kbd>）でファイルを選び <kbd>Enter</kbd>。Diffでは <kbd>n</kbd>/<kbd>p</kbd> でhunk移動、<kbd>b</kbd> でblameを表示します。<kbd>O</kbd> のツールメニュー内で <kbd>c</kbd> を押してエディタを設定します。GUIでの編集後はHomeまたは詳細で <kbd>r</kbd>。端末内ツールから戻ると差分ファイル一覧も更新し、対象が残っていれば選択ファイルとスクロール位置を保ちます。')),
                (t('Resume a worktree', 'Worktreeの作業を再開する'), t('Home <kbd>W</kbd> lists local worktrees. Search with <kbd>/</kbd>, add a purpose note with <kbd>m</kbd>, toggle a favorite with <kbd>*</kbd>, and filter favorites with <kbd>f</kbd>. <kbd>Enter</kbd> opens tools in the selected worktree. The Repo Worktrees tab (<kbd>7</kbd>) instead opens its shell directly with <kbd>Enter</kbd>.', 'Homeの <kbd>W</kbd> でローカルWorktreeを一覧します。<kbd>/</kbd> で検索、<kbd>m</kbd> で用途メモ、<kbd>*</kbd> でお気に入り、<kbd>f</kbd> で絞り込み。<kbd>Enter</kbd> は選択Worktreeのツールメニューです。詳細のWorktreesタブ（<kbd>7</kbd>）では <kbd>Enter</kbd> で直接シェルを開きます。')),
                (t('Find a change across repositories', '変更をリポジトリ横断で探す'), t('Home <kbd>S</kbd> searches commit messages. Narrow it in the same prompt with <code>author:</code>, <code>path:</code>, <code>since:</code> and <code>until:</code> — every other word stays message text, and values with spaces are quoted. <code>author:</code> also finds the aliases <code>members.json</code> merges into that person. Select a result and press <kbd>Enter</kbd> to inspect its diff. This searches messages and commit metadata, not file contents. Use Home <kbd>M</kbd> for cross-repository contributor totals.', 'Homeの <kbd>S</kbd> でコミットメッセージを検索します。同じプロンプトに <code>author:</code>・<code>path:</code>・<code>since:</code>・<code>until:</code> を書いて絞り込めます。それ以外の語はメッセージ本文として扱い、空白を含む値は引用符で囲みます。<code>author:</code> は <code>members.json</code> で統合した別名にも一致します。結果を選んで <kbd>Enter</kbd> で差分を開きます。検索対象はメッセージとコミット情報で、ファイル内容ではありません。貢献者の横断集計はHomeの <kbd>M</kbd> です。')),
            ]),
            ("p", t('Keys depend on the screen: <kbd>f</kbd> fetches on Home, toggles full-file view in Diff, and filters favorites in Workspace. Use <kbd>?</kbd> for context help or the <a href="https://github.com/orapli/git-dashboard-tui/blob/main/docs/reference.md">complete keyboard/configuration reference</a>.',
                    'キーの意味は画面で異なります。<kbd>f</kbd> はHomeでfetch、Diffで全文表示、Workspaceでお気に入り絞り込みです。<kbd>?</kbd> の画面別ヘルプ、または<a href="https://github.com/orapli/git-dashboard-tui/blob/main/docs/reference.ja.md">操作・設定リファレンス</a>を参照してください。')),
        ]),
        ("freshness", t("Read status and refresh deliberately", "状態表示と更新の使い分け"), [
            ("cols", [
                (t('Needs attention', '要対応'), t('Unresolved conflicts, an operation in progress, a CI result on <em>this branch</em> classified as failure (failure, cancelled, timed_out, action_required), a registration that could not be read at all, a pull request waiting on your review, or changes requested on this branch\u2019s own pull request. <kbd>n</kbd> filters these rows and every flag has a matching reason line in the panel. Dirty files, ahead/behind counts, a draft pull request and an approved one deliberately do not qualify: behind alone would select nearly every repository.', '未解決コンフリクト、進行中のGit操作、<em>作業中のブランチ</em>で失敗扱いのCI結果（failure、cancelled、timed_out、action_required）、そもそも読み取れない登録、自分へのレビュー依頼、このブランチのPRへの変更要求が対象です。<kbd>n</kbd> で絞れ、各理由はパネルに文章で表示します。未コミット、ahead/behind、下書きPR、承認済みPRは意図的に含めません。behindだけでほぼ全リポジトリが該当してしまうためです。')),
                (t('Unverified', '未確認'), t('Local data has not loaded, or GitHub data is unavailable, unauthenticated, failed, unsupported or at least five minutes old. It does not mean clean or CI success. A cached CI failure can count as both attention and unverified.', 'ローカル情報の未取得、GitHubの未導入・未認証・取得失敗・非対応・取得から5分以上の経過等を示します。クリーンやCI成功という意味ではありません。古いCI失敗は要対応と未確認の両方に含まれる場合があります。')),
                (t('Counts and timestamps', '集計範囲と時刻'), t('Summary counts cover the current group and text search, before the attention-only filter. Categories can overlap. Local checked is the analysis time, not a network fetch time. CI checked time describes retrieved data, not when the run finished. Small terminals hide some context; enlarge the window.', '集計は現在のグループ・文字検索の範囲で、要対応フィルタ適用前の値です。区分は重複します。ローカル取得時刻は解析時刻で、ネットワークfetch時刻ではありません。CI取得時刻も実行終了時刻とは異なります。狭い端末では詳細が隠れるため、必要なら広げてください。')),
                (t('CI scope and PR signals', 'CIの対象とPR情報'), t('CI is the latest run gh returns <em>for the repository\u2019s current branch</em>, across workflows; the branch it describes is named next to the state. A detached HEAD is its own state — there is no branch to ask about — rather than a silent fall-back to a repository-wide run. No runs, fetch failure, timed out, unauthenticated, gh not installed and success are all distinct. Press <kbd>C</kbd> to open the run. Alongside the open-PR count the panel shows this branch\u2019s own pull request with its draft state and review decision, and how many pull requests are waiting on your review. PR lists request at most 100 entries: <code>100+</code> means at least 100, including exactly 100.', 'CIはghが返す<em>そのリポジトリの現在のブランチ</em>の最新1実行です（ワークフローは限定しません）。対象ブランチは状態の隣に表示します。detached HEADは「問い合わせるブランチがない」独立した状態として扱い、リポジトリ全体の実行で代用しません。実行なし・取得失敗・タイムアウト・未認証・gh未導入・成功はいずれも別の状態です。<kbd>C</kbd> で実行ページを開けます。オープンPR件数に加えて、このブランチ自身のPRとその下書き状態・レビュー判定、自分のレビュー待ちPR件数もパネルに表示します。PRは最大100件を取得し、ちょうど100件の場合も <code>100+</code> と表示します。')),
                (t('Reload, fetch, pull', '再読込・fetch・pull'), t('<kbd>r</kbd> rereads local data without git fetch. Home <kbd>f</kbd>/<kbd>F</kbd> fetch remote refs for one/the filtered repositories. <kbd>p</kbd>/<kbd>P</kbd> pull and may merge or rebase. Ahead/behind uses locally available upstream refs, so reload alone cannot discover new remote commits.', '<kbd>r</kbd> はgit fetchせずローカル情報を読み直します。Homeの <kbd>f</kbd>/<kbd>F</kbd> は1件／絞り込み中のリポジトリのリモート参照をfetchします。<kbd>p</kbd>/<kbd>P</kbd> はpullし、merge/rebaseする場合があります。ahead/behindは手元のupstream参照との比較なので、再読込だけでは新しいリモートコミットを検出できません。')),
            ]),
            ("p", t('GitHub uses a process-local five-minute cache after a successful check. Retries are tiered by what went wrong: one minute after a plain failure, three minutes after a timeout (the request already spent its whole ten-second budget on a link that has just proven slow), and the full five minutes when gh is missing or unauthenticated, since a minute cannot fix either. Expiry does not schedule a request: the next reload does. Home auto-refresh is off by default; Settings <kbd>i</kbd> cycles off / 30 seconds / 1 minute / 5 minutes. There is no dedicated force-GitHub-refresh key. Failed requests retain the last successful values with their old timestamps. Restarting clears the in-memory GitHub cache; disk snapshots may still appear until refreshed.',
                    'GitHubはプロセス内で成功後5分キャッシュします。再試行の間隔は原因によって変わります。通常の失敗は1分、タイムアウトは3分（10秒の上限を使い切った低速な回線であるため）、gh未導入・未認証は5分です（1分では解消しないため）。時間経過だけでは取得せず、その後の再読込で再試行します。Homeの自動更新は既定でオフで、設定の <kbd>i</kbd> でオフ／30秒／1分／5分を切り替えます。GitHubだけを強制更新するキーはありません。取得失敗時は前回成功値と古い取得時刻を保持します。再起動でGitHubのメモリ内キャッシュは消えますが、更新まではディスク上のスナップショットが表示される場合があります。')),
        ]),
        ("editor-examples", t("Editor command examples", "エディタコマンドの設定例"), [
            ("p", t('Press <kbd>O</kbd>, then <kbd>c</kbd>, enter a command, and confirm with <kbd>Enter</kbd>. Set waiting with <kbd>w</kbd> in the same menu. These are configuration examples, not a claim of integration testing with every editor.', ' <kbd>O</kbd> → <kbd>c</kbd> でコマンドを入力し <kbd>Enter</kbd> で保存します。同じメニューの <kbd>w</kbd> で終了待機を設定します。以下は設定例で、すべてのエディタとの実機連携を検証したものではありません。')),
            ("p", t('A command may also use <code>{file}</code>, <code>{line}</code>, <code>{branch}</code> and <code>{hash}</code>, so <code>code --goto "{file}:{line}"</code> opens the line you were reading rather than the repository root. A placeholder with no value in the current view cancels the launch and names it, instead of substituting an empty string. <kbd>x</kbd> keeps up to six commands of your own in the same menu, listed as <kbd>1</kbd> – <kbd>6</kbd>.',
                    'コマンドには <code>{file}</code>・<code>{line}</code>・<code>{branch}</code>・<code>{hash}</code> も使えます。<code>code --goto "{file}:{line}"</code> のように書けば、リポジトリルートではなく読んでいた行が開きます。その画面で値のないプレースホルダがある場合は、空文字で置換せず、どれが欠けているかを示して起動を中止します。<kbd>x</kbd> では同じメニューに独自コマンドを6件まで登録でき、<kbd>1</kbd> – <kbd>6</kbd> として並びます。')),
            ("cols", [
                ('VS Code', t('<code>code "{path}"</code> — wait off. To return after closing the editor target, use <code>code --wait "{path}"</code> and wait on.', '<code>code "{path}"</code> — 待機オフ。対象を閉じてから復帰する場合は <code>code --wait "{path}"</code> と待機オンを組み合わせます。')),
                ('Neovim / Vim', t('<code>nvim "{path}"</code> or <code>vim "{path}"</code> — wait on, so the editor owns the terminal until it exits.', '<code>nvim "{path}"</code> または <code>vim "{path}"</code> — 待機オン。エディタ終了まで端末を渡します。')),
                (t('Absolute path with spaces', '空白を含む絶対パス'), t('<code>"/opt/editor tools/editor" "{path}"</code>. On Windows use an actual executable, for example <code>"C:/Program Files/Neovim/bin/nvim.exe" "{path}"</code>, with wait on.', '<code>"/opt/editor tools/editor" "{path}"</code>。Windowsでは実行ファイルを指定します。例: <code>"C:/Program Files/Neovim/bin/nvim.exe" "{path}"</code>、待機オン。')),
            ]),
            ("p", t('Commands are split into a program and arguments; they are not shell scripts. Quoting is supported, but shell aliases, $HOME, ~, pipes and redirections are not expanded. Use an absolute executable path or an exact executable name on an absolute PATH entry. The repository path is appended if {path} is absent. Settings <kbd>c</kbd> configures the separate external diff command; its placeholders are documented in the reference.', 'コマンドは実行ファイルと引数に分解され、シェルスクリプトとしては実行しません。引用符には対応しますが、シェルのalias、$HOME、~、パイプ、リダイレクトは展開しません。実行ファイルの絶対パスか、絶対パスのPATH要素上にある正確なファイル名を使ってください。{path} がなければリポジトリパスを追加します。設定画面の <kbd>c</kbd> は別の外部diffコマンド用です。プレースホルダはリファレンスを参照してください。')),
        ]),
        ("platforms", t("Platform and SSH support", "OS・SSHの対応範囲"), [
            ("cols", [
                ('Linux / macOS', t('Local Git views, shell, editor and installed Git clients. Unix shells use $SHELL (fallback /bin/sh). Release archives cover Linux x86_64/ARM64 and macOS Intel/Apple Silicon.', 'ローカルGit表示、シェル、エディタ、導入済みGitクライアントに対応します。シェルは$SHELL（未設定時 /bin/sh）。配布対象はLinux x86_64/ARM64とmacOS Intel/Apple Siliconです。')),
                ('Windows', t('Core views are covered by Windows CI; releases target x64. Shell uses COMSPEC (fallback cmd.exe). Editor and Git-client lookup infers native .exe/.com suffixes, so ordinary lazygit.exe and gitui.exe installations on PATH work with the menu. Arbitrary PATHEXT script types are not inferred; use a native executable for editor commands, not a .cmd wrapper such as code.cmd.', '主要機能はWindows CIの対象で、配布対象はx64です。シェルはCOMSPEC（未設定時cmd.exe）。エディタ・Gitクライアントの検索はネイティブの.exe/.comを補完するため、PATH上の通常のlazygit.exe・gitui.exeをメニューから起動できます。任意のPATHEXTスクリプト形式は補完しません。エディタコマンドにはcode.cmd等の.cmdラッパーではなくネイティブ実行ファイルを指定してください。')),
                ('ssh://host/absolute/path', t('Remote status, log, diff and contributor analysis require local ssh, remote git and noninteractive key authentication. Local shell/editor/clients, GitHub PR/CI queries and the cross-repository Worktree workspace are unsupported for these entries. A local clone with an SSH origin is still a local repository and is not subject to these restrictions.', 'リモートの状態・ログ・差分・貢献者解析にはローカルのssh、接続先のgit、非対話の鍵認証が必要です。この形式の登録ではローカルシェル・エディタ・クライアント、GitHub PR/CI取得、横断Worktree一覧は非対応です。originがSSH URLのローカルクローンにはこの制限はありません。')),
                (t('Validation scope', '検証範囲'), t('CI runs Rust checks/tests on Linux x86_64/ARM64, macOS and Windows. The new tools/workspace flows were exercised in a Linux terminal with sample tools. This is not macOS/Windows GUI integration certification.', 'CIはLinux x86_64/ARM64・macOS・WindowsでRustのチェックとテストを実行します。新しいツール起動・Workspaceの操作はLinuxの端末とサンプルツールで確認しています。macOS/WindowsのGUI連携を実機検証済みという意味ではありません。')),
            ]),
        ]),
        ("troubleshooting", t("Troubleshooting: symptom → check → fix", "トラブルシューティング：症状 → 確認 → 対処"), [
            ("cols", [
                (t('GitHub missing, unauthenticated or failed', 'GitHub情報が出ない・未認証・取得失敗'), t('Run <code>gh auth status</code> in the same environment as the TUI. From the repository, run <code>gh pr list --limit 1</code> and <code>gh run list --limit 1</code> to check repository access. For a normal local login use <code>gh auth login --hostname github.com</code>. An injected GH_TOKEN/GITHUB_TOKEN takes precedence over stored login: replace it through your environment’s secret mechanism. Wait out the retry delay for that failure kind, then Home <kbd>r</kbd>. A run of \u201cfetch failed\u201d on a healthy setup was usually the old two-second budget; it is now ten seconds, and a genuine timeout is reported as timed out rather than failed.', 'TUIと同じ環境で <code>gh auth status</code> を実行します。リポジトリ内で <code>gh pr list --limit 1</code> と <code>gh run list --limit 1</code> を実行してアクセスを確認します。通常のローカル認証は <code>gh auth login --hostname github.com</code>。注入されたGH_TOKEN/GITHUB_TOKENは保存済み認証より優先するため、環境のシークレット管理で差し替えます。失敗の種類に応じた再試行間隔を待ってからHomeの <kbd>r</kbd> で再取得してください。正常な環境で「取得失敗」が続くのは従来の2秒という上限が原因のことが多く、現在は10秒です。実際のタイムアウトは「取得失敗」ではなくタイムアウトとして表示します。')),
                (t('Wrong CI branch or old values', 'CIブランチが違う・値が古い'), t('Compare the displayed branch and timestamp with <code>gh run list --branch "$(git branch --show-current)" --limit 1</code>. CI is scoped to the current branch, so a colleague\u2019s failing branch no longer raises a warning on your row; if the row says detached HEAD, check out a branch. A successful GitHub cache lasts five minutes; reload after expiry. After changing origin, Home <kbd>r</kbd> checks the new remote; cached values are separated by local path, remote configuration and the branch they were asked about.', '表示ブランチ・取得時刻と <code>gh run list --branch "$(git branch --show-current)" --limit 1</code> を比較します。CIは現在のブランチが対象なので、他人の失敗ブランチで警告が出ることはありません。detached HEADと表示される場合はブランチをチェックアウトしてください。成功キャッシュは5分なので経過後に再読込します。origin変更後はHomeの <kbd>r</kbd> で新しい接続先を確認します。キャッシュはローカルパス・リモート設定・問い合わせたブランチごとに分離されます。')),
                (t('Ahead/behind does not change after reload', '再読込しても同期差分が変わらない'), t('Inspect <code>git remote -v</code> and <code>git status -sb</code> in the repository. Use Home <kbd>f</kbd> to update its remote refs, then inspect status. Reload is not fetch; a branch without an upstream has no upstream comparison.', '対象内で <code>git remote -v</code> と <code>git status -sb</code> を確認します。Homeの <kbd>f</kbd> でリモート参照を更新してから状態を確認してください。再読込はfetchではなく、upstream未設定のブランチにはその比較がありません。')),
                (t('Changes missing after leaving a tool', 'ツールから戻っても変更が見えない'), t('Compare with <code>git status --short</code> in the tool’s directory. Terminal-tool return refreshes Home and the diff file list, including repositories registered through symlinks. For later GUI edits, return to Home or Repo and press <kbd>r</kbd>, then reopen Diff. Check that the tool edited the selected repository or worktree.', 'ツールの作業ディレクトリで <code>git status --short</code> と比較します。端末内ツール終了後は、シンボリックリンク経由の登録でもHomeと差分ファイル一覧を更新します。GUIで後から編集した場合はHomeまたは詳細で <kbd>r</kbd> を押し、Diffを開き直してください。ツールが選択したリポジトリ・Worktree内で編集しているかも確認します。')),
                (t('Tool not installed or terminal input conflicts', 'ツールが未導入扱い・端末入力が競合する'), t('On Unix check <code>command -v nvim</code>; on Windows use <code>where.exe nvim.exe</code>. Configure that absolute executable path with menu <kbd>c</kbd>. Enable <kbd>w</kbd> waiting for terminal editors. Shell aliases and relative PATH entries are not used. See the Windows limitations above.', 'Unixでは <code>command -v nvim</code>、Windowsでは <code>where.exe nvim.exe</code> で確認し、その実行ファイルの絶対パスをメニューの <kbd>c</kbd> に設定します。端末内エディタは <kbd>w</kbd> で待機をオンにしてください。シェルaliasや相対PATH要素は使いません。Windowsの制限は上表を参照してください。')),
                (t('Registration or preferences do not persist', '登録や設定が保存されない'), t('Check the error and configuration-directory permissions. When GIT_DASHBOARD_CONFIG_DIR points to a missing directory, saving configuration creates it, including parent directories. Its nearest existing parent must be writable. Use the reference’s isolated-config commands. Preserve config.json, members.json and prefs.json when troubleshooting; removing cache files is not a settings reset.', 'エラーと設定先ディレクトリの権限を確認します。GIT_DASHBOARD_CONFIG_DIRの指定先が存在しない場合、設定保存時に親ディレクトリも含めて作成します。最も近い既存の親ディレクトリに書込権限が必要です。リファレンスに設定分離コマンドがあります。調査時はconfig.json・members.json・prefs.jsonを保持してください。cacheの削除は設定リセットではありません。')),
                (t('Worktree missing or errors counted', 'Worktreeがない・エラー件数が出る'), t('Run <code>git -C /absolute/repository worktree list --porcelain</code> for each registered local repository. Check missing paths and access rights. SSH entries are excluded. The error panel remains visible alongside healthy rows. A row whose own directory could not be inspected reads <code>unknown</code>, is counted in the header\u2019s <code>unknown</code> total rather than as a clean worktree, and carries its reason; <kbd>[</kbd>/<kbd>]</kbd> steps through the repositories that could not be listed and then those rows. Press Workspace <kbd>r</kbd> after resolving the error.', '登録したローカルリポジトリごとに <code>git -C /absolute/repository worktree list --porcelain</code> を実行し、パスの存在と権限を確認します。SSH登録は対象外です。正常な行がある場合もエラーパネルを表示します。ディレクトリを参照できなかった行は <code>unknown</code> と表示し、クリーンなWorktreeではなくヘッダーの <code>unknown</code> に数え、理由を保持します。<kbd>[</kbd>/<kbd>]</kbd> で一覧できなかったリポジトリと、それらの行を順に確認してください。解決後はWorkspaceの <kbd>r</kbd> で再取得します。')),
                (t('SSH repository cannot load', 'SSH登録を読み込めない'), t('Test <code>ssh -o BatchMode=yes host git --version</code>, then <code>ssh -o BatchMode=yes host "git -C /absolute/repository status --short"</code>. Configure keys, host trust and the remote path outside the TUI. The app never prompts for an SSH password.', '<code>ssh -o BatchMode=yes host git --version</code>、次に <code>ssh -o BatchMode=yes host "git -C /absolute/repository status --short"</code> を確認します。鍵・接続先の信頼設定・リモートパスはTUIの外で設定してください。TUIはSSHパスワードを要求しません。')),
                (t('Command missing, old features, or macOS launch blocked', '起動できない・新機能がない・macOSでブロックされる'), t('Check <code>command -v git-dashboard-tui</code> (Windows: <code>where.exe git-dashboard-tui</code>) for an older binary earlier on PATH. Add the install directory to PATH or run the binary by its full path. Compare the installed release with the version section above. On macOS, allow the downloaded app in System Settings → Privacy &amp; Security if Gatekeeper blocked it.', '<code>command -v git-dashboard-tui</code>（Windows: <code>where.exe git-dashboard-tui</code>）でPATH上に古い実行ファイルがないか確認します。導入先をPATHに追加するか絶対パスで起動してください。上のバージョン説明と導入したリリースを照合します。macOSのGatekeeperにブロックされた場合はシステム設定 → プライバシーとセキュリティから許可してください。')),
            ]),
            ("p", t('If unresolved, report the OS, installation method and release/commit, screen and keys used, expected/actual behavior, and complete error text. Remove credentials and private repository URLs before sharing logs.', '解決しない場合はOS、導入方法とリリース／コミット、画面と操作キー、期待結果と実際の結果、エラー全文を報告してください。ログを共有する前に認証情報や非公開リポジトリURLを除いてください。')),
        ]),
    ]
